name: Weekly Progress Report

on:
  schedule:
    - cron: '0 16 * * SUN'  # Runs at 16:00 UTC (9:00 PST) every Sunday
  workflow_dispatch:  # Allows manual triggering

jobs:
  send-report:
    runs-on: ubuntu-latest
    
    steps:
      - name: Send Weekly Report
        run: |
          curl -X POST ${{ secrets.VERCEL_URL }}/api/weekly-report \
            -H "Authorization: Bearer ${{ secrets.REPORT_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"email": "${{ secrets.REPORT_EMAIL }}"}' 